#!/bin/sh
# Program:
#       Make the command "tail" output with keyword hightlight.
# History:
#       2017/08/29, Henry Lou release.


useage="\
useage:
    tailh [options] file
example:
    tailh -e \"hello\" --regex=\"world\" demo
options:
    -e, --regex=pattern      Hightlight the pattern word.
    -i, --ignore-case        Case insensitive.
"
regex=""
ignore=""
head=0

until [ $# = 1 ]
do
    case "$1" in
        -e )
            if [ $head -eq 0 ] ; then
                regex=${regex}$2
                head=1
            else
                regex=${regex}"|"$2
            fi
            shift
            ;;
        --regex=* )
            if [ $head -eq 0 ] ; then
                regex=${regex}${1#*=}
                head=1
            else
                regex=${regex}"|"${1#*=}
            fi
            ;;
        -i | --ignore-case )
            ignore="(?i)"
            ;;
        * )
            echo "${useage}"
            exit 1
            ;;
    esac
    shift
done

if [ -f "$1" ]; then
    file="$1" 
else
    echo "${useage}"
    exit 1
fi
    
if [ $head -eq 0 ] ; then
    tail -f ${file} 
else
    tail -f ${file} | perl -pe "s/(${ignore}${regex})/\e[1;31m\$1\e[0m/g"
fi
